apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: kas-kelas
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://user:password@cluster.mongodb.net/kas-kelas"
  FONNTE_API_TOKEN: "your-fonnte-token-here"
  JWT_SECRET: "change-this-secret-key-minimum-32-chars"
  BASE_URL: "https://kas-kelas.yourdomain.com"